version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: dcdp_db
      POSTGRES_USER: dcdp_user
      POSTGRES_PASSWORD: dcdp_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A dcdp worker -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - web
      - redis

volumes:
  postgres_data:
