# Generated by Django 5.2.1 on 2025-05-27 16:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PcapFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="pcap_files/")),
                ("file_size", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("queued", "Queued for Analysis"),
                            ("analyzing", "Analyzing"),
                            ("completed", "Analysis Complete"),
                            ("failed", "Analysis Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("analysis_started_at", models.DateTimeField(blank=True, null=True)),
                ("analysis_completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="NetworkConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_ip", models.GenericIPAddressField()),
                ("destination_ip", models.GenericIPAddressField()),
                ("source_port", models.IntegerField()),
                ("destination_port", models.IntegerField()),
                ("protocol", models.CharField(max_length=10)),
                ("bytes_transferred", models.BigIntegerField()),
                ("packets_count", models.IntegerField()),
                ("timestamp", models.DateTimeField()),
                ("duration", models.FloatField(default=0.0)),
                ("avg_packet_size", models.FloatField(default=0.0)),
                ("std_packet_size", models.FloatField(default=0.0)),
                ("avg_inter_arrival", models.FloatField(default=0.0)),
                ("std_inter_arrival", models.FloatField(default=0.0)),
                ("unique_tcp_flags", models.IntegerField(default=0)),
                ("syn_count", models.IntegerField(default=0)),
                ("rst_count", models.IntegerField(default=0)),
                ("bytes_per_second", models.FloatField(default=0.0)),
                ("packets_per_second", models.FloatField(default=0.0)),
                (
                    "pcap_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="core.pcapfile",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_packets", models.IntegerField()),
                ("total_bytes", models.BigIntegerField()),
                ("duration", models.FloatField()),
                ("protocol_distribution", models.JSONField(default=dict)),
                ("top_sources", models.JSONField(default=list)),
                ("top_destinations", models.JSONField(default=list)),
                ("timeline_data", models.JSONField(default=list)),
                ("analysis_duration", models.FloatField()),
                ("ml_analysis", models.JSONField(default=dict)),
                ("threat_analysis", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pcap_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_result",
                        to="core.pcapfile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThreatDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "threat_type",
                    models.CharField(
                        choices=[
                            ("port_scan", "Port Scan"),
                            ("enhanced_port_scan", "Enhanced Port Scan"),
                            ("ddos", "DDoS Attack"),
                            ("ml_ddos", "ML-Detected DDoS"),
                            ("malware_comm", "Malware Communication"),
                            ("dns_tunneling", "DNS Tunneling"),
                            ("dns_dga", "DNS Domain Generation Algorithm"),
                            ("data_exfiltration", "Data Exfiltration"),
                            ("brute_force", "Brute Force Attack"),
                            ("ml_anomaly", "ML Anomaly Detection"),
                            ("behavioral_anomaly", "Behavioral Anomaly"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("source_ip", models.GenericIPAddressField()),
                ("destination_ip", models.GenericIPAddressField()),
                ("confidence_score", models.FloatField()),
                ("packet_count", models.IntegerField()),
                ("first_seen", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
                ("description", models.TextField()),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "pcap_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threats",
                        to="core.pcapfile",
                    ),
                ),
            ],
            options={
                "ordering": ["-first_seen"],
            },
        ),
    ]
