# Generated by Django 5.2.1 on 2025-05-29 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("binary", "Binary Classification (Benign/Malicious)"),
                            ("multiclass", "Multi-class Classification (Attack Types)"),
                            ("anomaly", "Anomaly Detection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("algorithm", models.CharField(max_length=50)),
                ("version", models.CharField(max_length=20)),
                ("file_path", models.CharField(max_length=500)),
                ("accuracy", models.FloatField(default=0.0)),
                ("precision", models.FloatField(default=0.0)),
                ("recall", models.FloatField(default=0.0)),
                ("f1_score", models.FloatField(default=0.0)),
                ("training_samples", models.IntegerField(default=0)),
                ("training_data_size", models.IntegerField(default=0)),
                ("feature_count", models.IntegerField(default=0)),
                ("hyperparameters", models.JSONField(default=dict)),
                ("evaluation_metrics", models.JSONField(default=dict)),
                ("feature_importance", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NetworkStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_bucket", models.DateTimeField()),
                ("packet_count", models.IntegerField(default=0)),
                ("byte_count", models.BigIntegerField(default=0)),
                ("flow_count", models.IntegerField(default=0)),
                ("tcp_packets", models.IntegerField(default=0)),
                ("udp_packets", models.IntegerField(default=0)),
                ("icmp_packets", models.IntegerField(default=0)),
                ("other_packets", models.IntegerField(default=0)),
                ("benign_flows", models.IntegerField(default=0)),
                ("malicious_flows", models.IntegerField(default=0)),
                ("high_confidence_threats", models.IntegerField(default=0)),
                ("top_source_ips", models.JSONField(default=list)),
                ("top_destination_ips", models.JSONField(default=list)),
                ("top_ports", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["time_bucket"],
            },
        ),
        migrations.RemoveField(
            model_name="networkconnection",
            name="avg_inter_arrival",
        ),
        migrations.RemoveField(
            model_name="networkconnection",
            name="avg_packet_size",
        ),
        migrations.RemoveField(
            model_name="networkconnection",
            name="bytes_per_second",
        ),
        migrations.RemoveField(
            model_name="networkconnection",
            name="bytes_transferred",
        ),
        migrations.RemoveField(
            model_name="networkconnection",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="networkconnection",
            name="packets_count",
        ),
        migrations.RemoveField(
            model_name="networkconnection",
            name="packets_per_second",
        ),
        migrations.RemoveField(
            model_name="networkconnection",
            name="rst_count",
        ),
        migrations.RemoveField(
            model_name="networkconnection",
            name="std_inter_arrival",
        ),
        migrations.RemoveField(
            model_name="networkconnection",
            name="std_packet_size",
        ),
        migrations.RemoveField(
            model_name="networkconnection",
            name="syn_count",
        ),
        migrations.RemoveField(
            model_name="networkconnection",
            name="unique_tcp_flags",
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="attack_type_distribution",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="benign_flows",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="bytes_per_second",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="flows_per_second",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="malicious_flows",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="ack_flag_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="act_data_pkt_fwd",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="active_max",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="active_mean",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="active_min",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="active_std",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="attack_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="average_packet_size",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="avg_bwd_segment_size",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="avg_fwd_segment_size",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="bwd_blk_rate_avg",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="bwd_byts_per_bulk_avg",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="bwd_header_length",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="bwd_iat_max",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="bwd_iat_mean",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="bwd_iat_min",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="bwd_iat_std",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="bwd_iat_total",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="bwd_packet_length_max",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="bwd_packet_length_mean",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="bwd_packet_length_min",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="bwd_packet_length_std",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="bwd_packets_per_second",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="bwd_pkts_per_bulk_avg",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="bwd_psh_flags",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="bwd_urg_flags",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="confidence_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="cwe_flag_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="down_up_ratio",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="ece_flag_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="fin_flag_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="flow_duration",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="flow_iat_max",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="flow_iat_mean",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="flow_iat_min",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="flow_iat_std",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="fwd_blk_rate_avg",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="fwd_byts_per_bulk_avg",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="fwd_header_length",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="fwd_iat_max",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="fwd_iat_mean",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="fwd_iat_min",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="fwd_iat_std",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="fwd_iat_total",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="fwd_packet_length_max",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="fwd_packet_length_mean",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="fwd_packet_length_min",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="fwd_packet_length_std",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="fwd_packets_per_second",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="fwd_pkts_per_bulk_avg",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="fwd_psh_flags",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="fwd_urg_flags",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="idle_max",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="idle_mean",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="idle_min",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="idle_std",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="init_win_bytes_backward",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="init_win_bytes_forward",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="is_malicious",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="max_packet_length",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="min_packet_length",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="min_seg_size_forward",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="packet_length_mean",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="packet_length_std",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="packet_length_variance",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="psh_flag_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="rst_flag_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="subflow_bwd_bytes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="subflow_bwd_packets",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="subflow_fwd_bytes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="subflow_fwd_packets",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="syn_flag_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="total_backward_packets",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="total_fwd_packets",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="total_length_bwd_packets",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="total_length_fwd_packets",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkconnection",
            name="urg_flag_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="threatdetection",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threats",
                to="core.networkconnection",
            ),
        ),
        migrations.AlterField(
            model_name="threatdetection",
            name="threat_type",
            field=models.CharField(
                choices=[
                    ("benign", "Benign Traffic"),
                    ("ddos", "DDoS Attack"),
                    ("port_scan", "Port Scan"),
                    ("brute_force", "Brute Force"),
                    ("web_attack_bruteforce", "Web Attack - Brute Force"),
                    ("web_attack_xss", "Web Attack - XSS"),
                    ("web_attack_sql_injection", "Web Attack - SQL Injection"),
                    ("infiltration", "Infiltration"),
                    ("bot", "Bot"),
                    ("dos_hulk", "DoS Hulk"),
                    ("dos_goldeneye", "DoS GoldenEye"),
                    ("dos_slowhttptest", "DoS Slow HTTP Test"),
                    ("dos_slowloris", "DoS Slowloris"),
                    ("heartbleed", "Heartbleed"),
                    ("ssh_patator", "SSH-Patator"),
                    ("ftp_patator", "FTP-Patator"),
                    ("ml_anomaly", "ML Anomaly Detection"),
                    ("behavioral_anomaly", "Behavioral Anomaly"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="analysisresult",
            index=models.Index(
                fields=["created_at"], name="core_analys_created_39183a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="networkconnection",
            index=models.Index(
                fields=["source_ip", "destination_ip"],
                name="core_networ_source__2c233a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="networkconnection",
            index=models.Index(
                fields=["timestamp"], name="core_networ_timesta_a90567_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="networkconnection",
            index=models.Index(
                fields=["is_malicious"], name="core_networ_is_mali_9f1677_idx"
            ),
        ),
        migrations.AddField(
            model_name="threatdetection",
            name="detected_by_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.mlmodel",
            ),
        ),
        migrations.AddIndex(
            model_name="threatdetection",
            index=models.Index(
                fields=["threat_type", "severity"],
                name="core_threat_threat__12dbc5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="threatdetection",
            index=models.Index(
                fields=["source_ip"], name="core_threat_source__372b81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="threatdetection",
            index=models.Index(
                fields=["first_seen"], name="core_threat_first_s_c545f6_idx"
            ),
        ),
        migrations.AddField(
            model_name="networkstatistics",
            name="pcap_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statistics",
                to="core.pcapfile",
            ),
        ),
        migrations.AddIndex(
            model_name="networkstatistics",
            index=models.Index(
                fields=["time_bucket"], name="core_networ_time_bu_b7a17a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="networkstatistics",
            index=models.Index(
                fields=["pcap_file", "time_bucket"],
                name="core_networ_pcap_fi_c3447e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="networkstatistics",
            unique_together={("pcap_file", "time_bucket")},
        ),
    ]
